---
title: Fundamental Belarusan
timezone: France/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
maininstitutesite: 
author: © 2004 Christian Cardell Marchant. This is an archived cope of the website [vitba.org](https://vitba.org). Free licence: [FDL](gnufreedl.html).
simple_search: http://google.com/search
markdown: kramdown
permalink: "/articles/:short_year/:title"
excerpt_separator: "<!--more-->"
exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- UploadToGithub.Rakefile
- README.md
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
